version: '3.1'
services:
  mongodb:
    image: "mongo"
    volumes: 
    - data:/data/db

  backend:
    build: ./Server_Side
    ports:
      - "80:80"
    volumes:
      - logs:/app/logs
      - ./Server_Side:/app
      - /app/node_modules
    depends_on:
      - mongodb
  frontend:
    build: ./Client_Side/Root
    ports:
      - "3000:5173"
    volumes:
      - ./Client_Side/Root/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: sujit
      ME_CONFIG_BASICAUTH_PASSWORD: sujit

volumes:
  data:
  logs:
